const config = {
    unlocks: [
        { stars: 3, type: 'mode', key: 'flashlight', emoji: '🔦' },
        { stars: 10, type: 'theme', key: 'dog', emoji: '🐕' },
        { stars: 30, type: 'theme', key: 'catsAndMice', emoji: '🐈' },
        { stars: 50, type: 'mode', key: 'ghost', emoji: '👻' },
        { stars: 70, type: 'theme', key: 'football', emoji: '⚽' },
        { stars: 100, type: 'theme', key: 'forest', emoji: '🐿️' },
        { stars: 150, type: 'mode', key: 'timer', emoji: '⏰' },
        { stars: 200, type: 'theme', key: 'sea', emoji: '🐬' },
        { stars: 250, type: 'theme', key: 'desert', emoji: '🐪' },
        { stars: 300, type: 'mode', key: 'all-in-one', emoji: '🗺️🔦👻⏰' },
        { stars: 350, type: 'theme', key: 'new_year', emoji: '🎄' },
        { stars: 400, type: 'mode', key: 'minotaur', emoji: '🐂' },
        { stars: 465, type: 'final', key: 'crown', emoji: '👑' }
    ],
    backgrounds:['/assets/images/abstract-design-element-pink-3595.png','/assets/images/abstract-design-element-blue-purple-3588.png','/assets/images/abstract-design-element-pink-3599.png','/assets/images/abstract-design-element-pink-orange-3585.png','/assets/images/abstract-design-element-purple-3557.png','/assets/images/abstract-design-element-purple-3560.png','/assets/images/abstract-design-element-purple-3569.png','/assets/images/abstract-design-element-purple-3570.png','/assets/images/abstract-design-element-shape-purple-3463.png','/assets/images/abstract-design-element-shape-yellow-3472.png','/assets/images/abstract-design-element-shape-yellow-3474.png','/assets/images/abstract-design-element-yellow-orange-3575.png','/assets/images/abstract-design-element-yellow-orange-3577.png','/assets/images/design-element-wave-blue-3689.png'],
    levels_portrait: [
    { h: 8, w: 6, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 9, w: 7, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'prim' },
    { h: 9, w: 7, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 10, w: 8, bonuses: 1, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 10, w: 8, bonuses: 2, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 11, w: 9, bonuses: 3, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 11, w: 9, bonuses: 3, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 12, w: 9, bonuses: 3, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 12, w: 9, bonuses: 4, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 13, w: 10, bonuses: 4, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 13, w: 10, bonuses: 4, visibility: { h: 3, w: 3 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 14, w: 11, bonuses: 5, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 14, w: 11, bonuses: 5, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 15, w: 12, bonuses: 5, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 15, w: 12, bonuses: 5, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 16, w: 12, bonuses: 6, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 16, w: 12, bonuses: 6, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 17, w: 13, bonuses: 6, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 18, w: 14, bonuses: 6, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 18, w: 14, bonuses: 6, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 19, w: 15, bonuses: 7, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 19, w: 15, bonuses: 7, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 20, w: 16, bonuses: 7, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 20, w: 16, bonuses: 7, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 21, w: 16, bonuses: 7, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 21, w: 16, bonuses: 8, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 22, w: 17, bonuses: 8, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 22, w: 17, bonuses: 8, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 23, w: 18, bonuses: 8, visibility: { h: 5, w: 5 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 23, w: 18, bonuses: 9, visibility: { h: 6, w: 6 }, timer: 99, ghosts: 3, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' }
],
    levels_landscape: [
    { h: 4, w: 7, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 5, w: 9, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'prim' },
    { h: 5, w: 9, bonuses: 0, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 2, h: 2 }, mazeAlgorithm: 'sidewinder' },
    { h: 5, w: 9, bonuses: 1, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 6, w: 11, bonuses: 2, visibility: { h: 3, w: 3 }, timer: 30, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 6, w: 11, bonuses: 2, visibility: { h: 3, w: 3 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 6, w: 11, bonuses: 2, visibility: { h: 4, w: 4 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'minotaurLair' },
    { h: 7, w: 13, bonuses: 3, visibility: { h: 4, w: 4 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 7, w: 13, bonuses: 3, visibility: { h: 4, w: 4 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 7, w: 13, bonuses: 4, visibility: { h: 4, w: 4 }, timer: 60, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 8, w: 15, bonuses: 4, visibility: { h: 4, w: 4 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 8, w: 15, bonuses: 4, visibility: { h: 5, w: 5 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 8, w: 15, bonuses: 4, visibility: { h: 5, w: 5 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 9, w: 16, bonuses: 4, visibility: { h: 5, w: 5 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'minotaurLair' },
    { h: 9, w: 16, bonuses: 5, visibility: { h: 5, w: 5 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 9, w: 16, bonuses: 5, visibility: { h: 6, w: 6 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 10, w: 18, bonuses: 5, visibility: { h: 6, w: 6 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 10, w: 18, bonuses: 5, visibility: { h: 6, w: 6 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 10, w: 18, bonuses: 6, visibility: { h: 6, w: 6 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 11, w: 20, bonuses: 6, visibility: { h: 7, w: 7 }, timer: 90, ghosts: 1, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 11, w: 20, bonuses: 6, visibility: { h: 6, w: 6 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'minotaurLair' },
    { h: 11, w: 20, bonuses: 6, visibility: { h: 6, w: 6 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 12, w: 22, bonuses: 6, visibility: { h: 6, w: 6 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 12, w: 22, bonuses: 6, visibility: { h: 6, w: 6 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 12, w: 22, bonuses: 7, visibility: { h: 7, w: 7 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 13, w: 24, bonuses: 7, visibility: { h: 6, w: 7 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 13, w: 24, bonuses: 7, visibility: { h: 6, w: 7 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' },
    { h: 13, w: 24, bonuses: 7, visibility: { h: 6, w: 7 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'sidewinder' },
    { h: 14, w: 26, bonuses: 7, visibility: { h: 6, w: 7 }, timer: 99, ghosts: 2, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'recursiveBacktracker' },
    { h: 14, w: 26, bonuses: 8, visibility: { h: 7, w: 7 }, timer: 99, ghosts: 3, ghostPatrol: { w: 3, h: 3 }, mazeAlgorithm: 'prim' }
],
    levels_minotaur_portrait: [
        {w: 9, h: 13, visibility: {w: 4, h: 4}, timer: 60, minotaurs: 1, bonuses: 1, mazeAlgorithm: 'minotaurLair'},
        {w: 11, h: 15, visibility: {w: 4, h: 4}, timer: 75, minotaurs: 1, bonuses: 2, mazeAlgorithm: 'minotaurLair'},
        {w: 13, h: 17, visibility: {w: 3, h: 3}, timer: 90, minotaurs: 2, bonuses: 3, mazeAlgorithm: 'minotaurLair'},
        {w: 15, h: 19, visibility: {w: 3, h: 3}, timer: 99, minotaurs: 2, bonuses: 3, mazeAlgorithm: 'minotaurLair'},
        {w: 17, h: 23, visibility: {w: 2, h: 2}, timer: 99, minotaurs: 3, bonuses: 3, mazeAlgorithm: 'minotaurLair'}
    ],
    levels_minotaur_landscape: [
        {w: 13, h: 9, visibility: {w: 4, h: 4}, timer: 60, minotaurs: 1, bonuses: 1, mazeAlgorithm: 'minotaurLair'},
        {w: 15, h: 11, visibility: {w: 4, h: 4}, timer: 75, minotaurs: 1, bonuses: 2, mazeAlgorithm: 'minotaurLair'},
        {w: 17, h: 13, visibility: {w: 3, h: 3}, timer: 90, minotaurs: 2, bonuses: 2, mazeAlgorithm: 'minotaurLair'},
        {w: 19, h: 15, visibility: {w: 3, h: 3}, timer: 99, minotaurs: 2, bonuses: 3, mazeAlgorithm: 'minotaurLair'},
        {w: 23, h: 17, visibility: {w: 9, h: 9}, timer: 99, minotaurs: 1, bonuses: 3, mazeAlgorithm: 'minotaurLair'}
    ],
    themes: {
        dog:{name:'Dog',player:'🐕',finish:'🏠',walls:['🏡','🌳','💧','🌿'],decor:['🐾', '🦴'],gradient:['#FADDAA','#EDC967']},
        forest:{name:'Forest',player:'🐿️',finish:'🌰',walls:['🌲','🌳','🍄','🍁'],decor:[,'🍄','🍁'],gradient:['#D9EAD3','#B6D7A8']},
        jungle:{name:'Jungle',player:'🐒',finish:'🍌',walls:['?','','🌴','🌸'],decor:['🌺','🦋'],gradient:['#D4F0C4','#A0D8A0']},
        antarctica:{name:'Antarctica',player:'🐧',finish:'❤️',walls:['❄️','🧊'],decor:['🧊','❄️'],gradient:['#E6F3FB','#B0C4DE']},
        catsAndMice:{name:'Cats & Mice',player:'🐈',finish:'🐀',walls:['🌲','🏠','🌿','🐾'],decor:['🧶','🧀'],gradient:['#FFFACD','#F5DEB3']},
        snail:{name:'Snail',player:'🐌',finish:'🥬',walls:['🌲','🌸','🍄','💧'],decor:['🐞','🌼'],gradient:['#DFF0D8','#BDECB6']},
        football:{name:'Football',player:'⚽',finish:'🥅',walls:['📣','🏆','👟'],decor:['🏆','🏅'],gradient:['#D9EAD3','#B6D7A8']},
        sea:{name:'Sea',player:'🐬',finish:'⭐',walls:['🌊','⛵','🏝️','🏖️'],decor:['🐠','🦀','🐚'],gradient:['#B2EBF2','#81D4FA']},
        desert:{name:'Desert',player:'🐪',finish:'🌴',walls:['🌵','🏜️','⛰️'],decor:['🌵'],gradient:['#FADDAA','#EDC967']},
        new_year:{name:'New Year',player:'🎁',finish:'🎄',walls:['❄️','⛄','🎅','🦌'],decor:['🌟','🔔'],gradient:['#A9B4C2','#E0F2F1']}
    },
    audio: {
        menu:'/assets/audio/light.ogg',
        game:['/assets/audio/kinderszenen.ogg','/assets/audio/mirlitons.ogg','/assets/audio/dogsandcats.ogg','/assets/audio/theskaterswaltz.ogg','/assets/audio/walkinganddancing.ogg'],
        victorySfx:['/assets/audio/sfx-piano-bar2.ogg','/assets/audio/sfx-sfx-strings7.ogg'],
        collectSfx:'/assets/audio/sfx-magic15.ogg',
        defeatSfx:'/assets/audio/sfx-pop2.ogg',
        timerWarningSfx:'/assets/audio/sfx-clock.ogg',
        timerDefeatSfx:'/assets/audio/sfx-cartoons19.ogg',
        minotaurMusic: '/assets/audio/aquarium.ogg',
        minotaurVictoryMusic: '/assets/audio/sfx-piano-bar.ogg',
        unlockSfx: '/assets/audio/sfx-piano-coda3.ogg'
    },
    languageNames:{ru:'Русский',en:'English'},
    languages: {
        ru:{settings:'Настройки',themes:'Темы',random_theme:'Случайная тема',classic:'Классический',flashlight:'Фонарик',ghost:'Привидение',timer:'Таймер',minotaur: 'Минотавр', all_in_one:'Всё в одном',random_mode:'Случайный',menu:'Меню',retry:'Повторить',next_level:'Следующий',confirm_exit_title:'Выйти?',confirm_exit_text:'Прогресс уровня не будет сохранен.',select_mode:'Выберите режим',reset_progress:'Сбросить прогресс',confirm_reset_title:'Сбросить прогресс?',confirm_reset_text:'Все ваши звезды будут удалены. Это действие необратимо.',jungle:'Джунгли',antarctica:'Антарктика',catsAndMice:'Кошки-мышки',snail:'Улитка',football:'Футбол',sea:'Море',desert:'Пустыня',dog:'Собака',forest:'Лес',new_year: 'Новый год',color_theme:'Тема оформления',about_title:'О разработчике',about_text:'Emoji Maze - это увлекательная игра-головоломка, созданная для того, чтобы бросить вызов вашему пространственному мышлению и времени реакции. Игра разработана с использованием HTML5 Canvas, что обеспечивает плавную и отзывчивую графику как на настольных, так и на мобильных устройствах, а также на Android TV. Основное внимание уделяется простому и интуитивно понятному управлению, а также адаптивному дизайну. Цель игры - провести вашего персонажа-эмодзи через лабиринт, избегая привидений и собирая бонусы, чтобы достичь финиша. Наслаждайтесь игрой!', unlock_mode_message: 'Поздравляем! Вам теперь доступен новый режим игры: ', unlock_theme_message: 'Поздравляем! Вам теперь доступна новая тема: ', unlock_all_title: '💝', unlock_all_text: 'Поздравляем! Все режимы, темы и уровни теперь доступны.'},
        en:{settings:'Settings',themes:'Themes',random_theme:'Random Theme',classic:'Classic',flashlight:'Flashlight',ghost:'Ghost',timer:'Timer',minotaur: 'Minotaur', all_in_one:'All in One',random_mode:'Random',menu:'Menu',retry:'Retry',next_level:'Next Level',confirm_exit_title:'Exit?',confirm_exit_text:'Level progress will be lost.',select_mode:'Select Mode',reset_progress:'Reset Progress',confirm_reset_title:'Reset progress?',confirm_reset_text:'All your stars will be deleted. This action is irreversible.',jungle:'Jungle',antarctica:'Antarctica',catsAndMice:'Cats & Mice',snail:'Snail',football:'Football',sea:'Sea',desert:'Desert',dog:'Dog',forest:'Forest',new_year: 'New Year',color_theme:'Color Theme',about_title:'About Developer',about_text:'Emoji Maze is an engaging puzzle game designed to challenge your spatial reasoning and reaction time. The game is developed using HTML5 Canvas, ensuring smooth and responsive graphics across desktop, mobile, and Android TV devices. The focus is on simple, intuitive controls and adaptive design. Your goal is to guide your emoji character through the maze, avoiding ghosts and collecting bonuses to reach the finish line. Enjoy the game!', unlock_mode_message: 'Congratulations! You have unlocked a new game mode: ', unlock_theme_message: 'Congratulations! You have unlocked a new theme: ', unlock_all_title: '💝', unlock_all_text: 'Congratulations! All modes, themes, and levels are now available.'}
    }
};